$(function(){
    $('.red').mouseenter(function(){
        $('.red_hover').stop().css("opacity","1");
        $(this).siblings('.color_hover').stop().css("display","block");
    });
    $('.red').mouseleave(function(){
        $('.red_hover').stop().css("opacity","0");
    });
    $('.blue').mouseenter(function(){
        $('.blue_hover').stop().css("opacity","1");
    });
    $('.blue').mouseleave(function(){
        $('.blue_hover').stop().css("opacity","0");
    });
    $('.beige').mouseenter(function(){
        $('.beige_hover').stop().css("opacity","1");
    });
    $('.beige').mouseleave(function(){
        $('.beige_hover').stop().css("opacity","0");
    });
    $('.green').mouseenter(function(){
        $('.green_hover').stop().css("opacity","1");
    });
    $('.green').mouseleave(function(){
        $('.green_hover').stop().css("opacity","0");
    });
});